# Generated by Django 5.2.2 on 2025-09-25 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_projectreview_client_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Internal team member responsible for the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["author"], name="project_author__80fdfd_idx"),
        ),
    ]
