# Generated by Django 5.2.2 on 2025-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_author_project_project_author__80fdfd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Project sections with section_id, media_url, and description for detailed showcase",
            ),
        ),
    ]
