# Generated by Django 5.2.2 on 2025-10-16 15:38

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_sections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="projectgalleryimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main project screenshot or banner (JPG, JPEG, PNG, WEBP - Max 12MB)",
                null=True,
                upload_to="projects/featured/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    projects.models.validate_project_image_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="projectgalleryimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Gallery image (JPG, JPEG, PNG, WEBP - Max 12MB)",
                null=True,
                upload_to="projects/gallery/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    projects.models.validate_project_image_size,
                ],
            ),
        ),
    ]
