# Generated by Django 5.2.2 on 2025-10-16 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_remove_project_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "section_id",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("features", "Features"),
                            ("architecture", "Architecture"),
                            ("tech-stack", "Tech Stack"),
                            ("challenge", "Challenge"),
                            ("solution", "Solution"),
                            ("results", "Results"),
                            ("design", "Design Process"),
                            ("development", "Development"),
                            ("testimonial", "Testimonial"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type/identifier for this section",
                        max_length=50,
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom section name (optional, defaults to section_id)",
                        max_length=100,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        help_text="Public URL to media file (e.g., /media/projects/image.jpg or https://example.com/image.jpg)",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description for this section"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which sections appear (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this section is visible"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_sections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Section",
                "verbose_name_plural": "Project Sections",
                "db_table": "project_section",
                "ordering": ["project", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["project"], name="project_sec_project_0c3118_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="project_sec_sort_or_27b40f_idx"
                    ),
                ],
            },
        ),
    ]
