# Generated by Django 5.2.2 on 2025-10-16 17:43

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectsection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsection",
            name="media_url",
        ),
        migrations.AddField(
            model_name="projectsection",
            name="media",
            field=models.ImageField(
                blank=True,
                help_text="Section image (JPG, JPEG, PNG, WEBP - Max 10MB)",
                null=True,
                upload_to="projects/sections/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    projects.models.validate_section_image_size,
                ],
            ),
        ),
    ]
