# Generated by Django 5.2.2 on 2025-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_herosection_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About"),
                    ("services", "Services"),
                    ("blog", "Blog"),
                ],
                default="home",
                help_text="Page this hero section belongs to",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only one hero section should be active at a time per page",
            ),
        ),
    ]
