# Generated by Django 5.2.2 on 2025-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_herosection_page_alter_herosection_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object: { 'ig': '...', 'git': '...', 'linkedin': '...', 'x': '...', 'reddit': '...' }",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
                "db_table": "contact_info",
                "ordering": ["-date_created"],
            },
        ),
    ]
