# Generated by Django 5.2.2 on 2025-08-21 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contactinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "date_subscribed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Newsletter Subscription",
                "verbose_name_plural": "Newsletter Subscriptions",
                "db_table": "newsletter_subscription",
                "ordering": ["-date_subscribed"],
            },
        ),
    ]
