# Generated by Django 5.2.2 on 2025-08-21 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_newslettersubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.CharField(max_length=100)),
                ("stat_value", models.CharField(max_length=50)),
                ("stat_description", models.CharField(blank=True, max_length=200)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g., 'users', 'calendar', 'trophy')",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Statistic",
                "verbose_name_plural": "About Statistics",
                "db_table": "about_stats",
                "ordering": ["display_order", "stat_name"],
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone_title", models.CharField(max_length=200)),
                ("milestone_description", models.TextField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g., 'flag', 'target', 'rocket')",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Roadmap Milestone",
                "verbose_name_plural": "Roadmap Milestones",
                "db_table": "roadmap",
                "ordering": ["display_order", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_title", models.CharField(max_length=200)),
                ("reason_description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g., 'shield', 'zap', 'heart')",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Why Choose Us",
                "verbose_name_plural": "Why Choose Us",
                "db_table": "why_choose_us",
                "ordering": ["display_order", "reason_title"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("job_title", models.CharField(max_length=200)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "company_logo",
                    models.URLField(blank=True, help_text="URL to company logo image"),
                ),
                ("company_website", models.URLField(blank=True)),
                (
                    "start_month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                (
                    "start_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2035),
                        ]
                    ),
                ),
                (
                    "end_month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2035),
                        ],
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is your current position",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed job description and achievements"
                    ),
                ),
                (
                    "key_responsibilities",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of key responsibilities: ['Responsibility 1', 'Responsibility 2']",
                        null=True,
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of key achievements: ['Achievement 1', 'Achievement 2']",
                        null=True,
                    ),
                ),
                (
                    "technology_stack",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of technologies used: ['Python', 'Django', 'React']",
                        null=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True,
                        help_text="Display this experience in the main timeline",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order of display (0 = first, higher numbers = later)",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
                "db_table": "work_experience",
                "ordering": ["-start_year", "-start_month", "display_order"],
            },
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="show_roadmap",
            field=models.BooleanField(default=False, help_text="Show roadmap section"),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="show_stats",
            field=models.BooleanField(
                default=True, help_text="Show statistics section"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="show_why_choose_us",
            field=models.BooleanField(
                default=True, help_text="Show why choose us section"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="show_work_experience",
            field=models.BooleanField(
                default=True, help_text="Show work experience timeline"
            ),
        ),
    ]
