# Generated by Django 5.2.2 on 2025-10-16 12:16

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_supportticket_supportattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsection",
            name="media_url",
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="media",
            field=models.FileField(
                blank=True,
                help_text="Upload an image (JPG, JPEG, PNG) or video (MP4, MOV, etc.). Max size: 80MB.",
                null=True,
                upload_to=core.models.about_section_media_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "mp4",
                            "mov",
                            "avi",
                            "wmv",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
