# Generated by Django 5.2.2 on 2025-11-20 06:45

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_aboutsection_media_url_aboutsection_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="Background video for hero section (MP4, WebM recommended). Max size: 80MB.",
                null=True,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "mov", "avi"]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
