# Generated by Django 5.2.2 on 2025-11-21 19:19

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_herosection_hero_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="hero_video",
        ),
        migrations.AddField(
            model_name="herosection",
            name="media",
            field=models.FileField(
                blank=True,
                help_text="Background media for hero section - supports both images (jpg, png, webp) and videos (mp4, webm, mov, avi). Max size: 80MB.",
                null=True,
                upload_to="hero_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "webm",
                            "mov",
                            "avi",
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
    ]
