# Generated by Django 5.2.2 on 2025-11-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_herosection_hero_video_herosection_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whychooseus",
            name="icon_name",
        ),
        migrations.AddField(
            model_name="whychooseus",
            name="img",
            field=models.ImageField(
                blank=True,
                help_text="Upload an icon (SVG, PNG, JPG, etc.) for this feature",
                null=True,
                upload_to="why_choose_us_icons/",
            ),
        ),
    ]
