# Generated by Django 5.2.2 on 2025-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_whychooseus_icon_name_whychooseus_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(help_text="The FAQ question")),
                ("answer", models.TextField(help_text="The answer to the question")),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured FAQs appear at the top"
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Optional links related to this FAQ (e.g., {"Learn More": "https://example.com"})',
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active FAQs are shown to users"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "faqs",
                "ordering": ["-featured", "display_order", "-date_created"],
            },
        ),
    ]
