# Generated by Django 5.2.2 on 2026-01-01 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="end_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2036),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2036),
                ]
            ),
        ),
    ]
