# Generated by Django 5.2.2 on 2025-10-04 08:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="subcategory",
            field=models.CharField(
                blank=True,
                help_text="Optional subcategory ID from the service_category's sub_categories JSON field",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "short_desc",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the service category",
                    ),
                ),
                (
                    "sub_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of subcategories, each with id and name fields",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "db_table": "service_category",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="service_cat_slug_bad00b_idx"),
                    models.Index(
                        fields=["active"], name="service_cat_active_c6dc1b_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="service_cat_sort_or_19fac6_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The main category this service belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
    ]
