# Generated by Django 5.2.2 on 2025-10-04 09:19

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_subcategory_servicecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="category_url",
            field=models.ImageField(
                blank=True,
                help_text="Icon or image for the service category (max 3MB)",
                null=True,
                upload_to="category_icons/",
                validators=[services.models.validate_image_size],
            ),
        ),
    ]
