# Generated by Django 5.2.2 on 2025-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicecategory_category_url"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="service",
            name="service_categor_c7fde4_idx",
        ),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="subcategory",
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_category"], name="service_service_5f0c60_idx"
            ),
        ),
    ]
