# Generated by Django 5.2.2 on 2025-11-20 13:34

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_remove_service_service_categor_c7fde4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_image",
            field=models.ImageField(
                blank=True,
                help_text="Service card image (max 3MB). Recommended: 800x600px",
                null=True,
                upload_to="services/",
                validators=[services.models.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="img_url",
            field=models.TextField(
                blank=True, help_text="Legacy field - use service_image instead"
            ),
        ),
    ]
