# Generated by Django 5.2.2 on 2025-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                help_text="Profile image (Google or uploaded)",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
