# Generated by Django 5.2.2 on 2025-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Denormalized user balance for quick reads",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                help_text="Preferred currency code (e.g., USD, KSH)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language_preference",
            field=models.CharField(
                blank=True,
                default="English",
                help_text="Preferred language name (e.g., English)",
                max_length=32,
            ),
        ),
    ]
