# Generated by Django 5.2.2 on 2025-09-25 08:02

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_account_balance_user_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliate_code",
            field=models.CharField(
                blank=True,
                help_text="Optional affiliate/referral code for partner tracking",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professional_title", models.CharField(blank=True, max_length=150)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Primary domain or industry focus",
                        max_length=120,
                    ),
                ),
                ("professional_summary", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "social_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of social media profiles as objects: [{'name': 'linkedin', 'url': 'https://...'}]",
                        null=True,
                    ),
                ),
                (
                    "affiliate_clients",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "media_url",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="partners/media/",
                        validators=[accounts.models.validate_partner_media],
                    ),
                ),
                ("services", models.JSONField(blank=True, default=list, null=True)),
                ("orders", models.JSONField(blank=True, default=list, null=True)),
                ("blog_posts", models.JSONField(blank=True, default=list, null=True)),
                ("projects", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["-created_at"],
            },
        ),
    ]
