# Generated by Django 5.2.2 on 2025-09-25 12:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_affiliate_code_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="blog_posts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of BlogPost IDs authored or associated with this partner.",
                null=True,
                validators=[accounts.models.Partner._validate_id_list],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="orders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of Order IDs (may reference client orders).",
                null=True,
                validators=[accounts.models.Partner._validate_id_list],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="projects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of Project IDs linked to this partner.",
                null=True,
                validators=[accounts.models.Partner._validate_id_list],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="services",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of Service IDs (read-only exposure on public API).",
                null=True,
                validators=[accounts.models.Partner._validate_id_list],
            ),
        ),
    ]
