# Generated by Django 5.2.2 on 2025-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_partner_blog_posts_alter_partner_orders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Is two-factor authentication enabled for this user?",
            ),
        ),
    ]
