# Generated by Django 5.2.2 on 2025-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_two_factor_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_social_login",
            field=models.BooleanField(
                default=False,
                help_text="User authenticated via social login (Google, etc.)",
            ),
        ),
    ]
