# Generated by Django 5.2.2 on 2025-10-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_is_social_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("partner", "Partner"),
                    ("client", "Client"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
