# Generated by Django 5.2.2 on 2025-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_timezone",
            field=models.CharField(
                blank=True,
                default="GMT",
                help_text="User's timezone (e.g., GMT, America/New_York, Africa/Nairobi)",
                max_length=50,
            ),
        ),
    ]
