# Generated by Django 5.2.2 on 2025-10-16 15:38

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image_url",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image (JPG, JPEG, PNG, WEBP - Max 12MB)",
                null=True,
                upload_to="blog/featured/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    blog.models.validate_blog_image_size,
                ],
            ),
        ),
    ]
