# Generated by Django 5.2.2 on 2026-01-03 05:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blogpost_image_url_blogpost_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Full blog post content - supports rich text, code snippets, and images"
            ),
        ),
    ]
