# Generated by Django 5.2.2 on 2026-01-03 05:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="",
                help_text="Full blog post content - supports rich text, code snippets, and images",
            ),
        ),
    ]
