# Generated by Django 5.2.2 on 2026-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Pinned/featured comment for highlighting on the article page",
            ),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["featured"], name="blog_commen_feature_bcfcbe_idx"
            ),
        ),
    ]
