# Generated by Django 5.2.2 on 2025-08-17 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_delete_newslettersubscriber"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional file upload (max 15MB, pdf/doc/docx/txt/jpg/png/zip)",
                        null=True,
                        upload_to="service_requests/",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("project_description", models.TextField()),
                ("budget", models.CharField(blank=True, max_length=50)),
                ("timeline", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        help_text="Order derived from this service request (if converted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request",
                        to="business.order",
                    ),
                ),
                (
                    "pricing_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="services.servicepricingtier",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "db_table": "service_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
