# Generated by Django 5.2.2 on 2025-09-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_order_attachments_order_work_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paypal_order_id", models.CharField(max_length=255)),
                (
                    "paypal_payer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paypal_payer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "paypal_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paypal_status", models.CharField(default="CREATED", max_length=50)),
                ("paypal_intent", models.CharField(default="CAPTURE", max_length=20)),
                ("paypal_create_time", models.DateTimeField(blank=True, null=True)),
                ("paypal_update_time", models.DateTimeField(blank=True, null=True)),
                ("paypal_response", models.JSONField(blank=True, default=dict)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_details",
                        to="business.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Payment",
                "verbose_name_plural": "PayPal Payments",
                "db_table": "paypal_payment",
            },
        ),
    ]
