# Generated by Django 5.2.2 on 2025-09-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0009_remove_paypalpayment_paypal_response_payment_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountBalance",
        ),
    ]
