# Generated by Django 5.2.2 on 2025-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0010_delete_accountbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="citations",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="formatting_style",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(
                choices=[("technical", "Technical"), ("writing", "Writing")],
                default="technical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
