# Generated by Django 5.2.2 on 2025-12-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_user_timezone"),
        ("business", "0012_orderactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Partner/Agent assigned to handle this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="accounts.partner",
            ),
        ),
    ]
