# Generated by Django 5.2.2 on 2025-12-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0013_order_assigned_partner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
