# Generated by Django 5.2.2 on 2026-01-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_user_timezone"),
        ("business", "0014_delete_contactmessage"),
        ("products", "0001_initial"),
        ("services", "0005_service_service_image_alter_service_img_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                help_text="Unique order tracking number for customer-facing identification",
                max_length=50,
                unique=False,  # Don't enforce unique yet - will be added after backfill
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="order_order_n_06f120_idx"
            ),
        ),
    ]
