# Generated by Django 5.2.2 on 2026-01-01 18:06

from django.db import migrations
from datetime import datetime
from django.utils import timezone


def backfill_order_numbers(apps, schema_editor):
    """Backfill order_number for existing orders that don't have one"""
    Order = apps.get_model('business', 'Order')
    
    # Get all orders with empty order_number
    orders_to_update = Order.objects.filter(order_number='').order_by('date_created')
    
    # Group by date and generate numbers
    orders_by_date = {}
    for order in orders_to_update:
        date_key = order.date_created.date().strftime('%Y%m%d')
        if date_key not in orders_by_date:
            orders_by_date[date_key] = []
        orders_by_date[date_key].append(order)
    
    # Generate and save order numbers
    for date_key, date_orders in orders_by_date.items():
        for idx, order in enumerate(date_orders, 1):
            order.order_number = f"ORD-{date_key}-{str(idx).zfill(4)}"
            order.save(update_fields=['order_number'])


def reverse_backfill(apps, schema_editor):
    """Reverse backfill - clear generated order numbers"""
    Order = apps.get_model('business', 'Order')
    Order.objects.all().update(order_number='')


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0015_order_order_number_order_order_order_n_06f120_idx"),
    ]

    operations = [
        migrations.RunPython(backfill_order_numbers, reverse_backfill),
    ]
