# Generated by Django 5.2.2 on 2025-11-26 15:33

import django.db.models.deletion
import django.utils.timezone
import notifications.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        max_length=255,
                        validators=[notifications.models.validate_sender_name],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "message",
                    models.TextField(
                        validators=[notifications.models.validate_word_count]
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("service", "Service Request"),
                            ("consultation", "Book Free Consultation"),
                            ("tutoring", "Tutoring"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Auto-captured from request", null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Mapped from IP address (future feature)",
                        max_length=100,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent string from request",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user assigned to handle this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to in-system user who sent message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "db_table": "message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("client", "Client"), ("admin", "Admin")],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "reply_message",
                    models.TextField(
                        help_text="Reply text (max 1000 characters)", max_length=1000
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_replies",
                        to="notifications.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Reply",
                "verbose_name_plural": "Message Replies",
                "db_table": "message_reply",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="message_status_fbc084_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["subject"], name="message_subject_9482ad_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["assigned_to"], name="message_assigne_b1cb1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["user_id"], name="message_user_id_b56247_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="message_created_19da1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereply",
            index=models.Index(
                fields=["message"], name="message_rep_message_88f030_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereply",
            index=models.Index(
                fields=["created_at"], name="message_rep_created_8ce319_idx"
            ),
        ),
    ]
