# Generated by Django 5.2.2 on 2025-12-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0011_servicerequest_citations_and_more"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("contact", "Contact Message"), ("order", "Order Message")],
                default="contact",
                help_text="Type of message: contact inquiry or order communication",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is an order message, link to the order",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="business.order",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("service", "Service Request"),
                    ("consultation", "Book Free Consultation"),
                    ("tutoring", "Tutoring"),
                    ("partnership", "Partnership"),
                    ("order", "Order Communication"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["order", "message_type"], name="message_order_i_09a2b4_idx"
            ),
        ),
    ]
