# Generated by Django 5.2.2 on 2025-12-27 04:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import notifications.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_delete_contactmessage"),
        ("notifications", "0002_alter_message_options_message_message_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("whatsapp", "WhatsApp"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True, help_text="Admin's response to this contact message"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, help_text="When the admin replied", null=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "db_table": "contact_message",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="GeneralMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        max_length=255,
                        validators=[notifications.models.validate_sender_name],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "message",
                    models.TextField(
                        validators=[notifications.models.validate_word_count]
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("service", "Service Request"),
                            ("consultation", "Book Free Consultation"),
                            ("tutoring", "Tutoring"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Auto-captured from request", null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Mapped from IP address", max_length=100
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent string from request",
                        max_length=255,
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True,
                        help_text="Admin's response to this inquiry (one reply only)",
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, help_text="When the admin replied", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "General Message",
                "verbose_name_plural": "General Messages",
                "db_table": "general_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneralMessageAttachment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Allowed: images, PDF, TXT, Word (max 5MB)",
                        upload_to=notifications.models.general_message_attachment_path,
                        validators=[
                            notifications.models.validate_attachment_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "txt",
                                    "doc",
                                    "docx",
                                ]
                            ),
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "General Message Attachment",
                "verbose_name_plural": "General Message Attachments",
                "db_table": "general_message_attachment",
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Allowed: images, PDF, TXT, Word (max 5MB per file)",
                        upload_to=notifications.models.message_attachment_path,
                        validators=[
                            notifications.models.validate_attachment_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "txt",
                                    "doc",
                                    "docx",
                                ]
                            ),
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
                "db_table": "message_attachment",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "User Message",
                "verbose_name_plural": "User Messages",
            },
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_status_fbc084_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_subject_9482ad_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_assigne_b1cb1b_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_user_id_b56247_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="user_messag_order_i_04260b_idx",
            old_name="message_order_i_09a2b4_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="user_messag_created_53dd6f_idx",
            old_name="message_created_19da1c_idx",
        ),
        migrations.RemoveField(
            model_name="message",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="message",
            name="country",
        ),
        migrations.RemoveField(
            model_name="message",
            name="device",
        ),
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender_name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="messagereply",
            name="reply_message",
        ),
        migrations.RemoveField(
            model_name="messagereply",
            name="sender_name",
        ),
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default="", help_text="Message text content"),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Has the message been read by the recipient"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("support", "Support"),
                    ("system", "System"),
                ],
                default="user",
                help_text="Who sent the message",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who owns this message thread",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagereply",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Has this reply been read"
            ),
        ),
        migrations.AddField(
            model_name="messagereply",
            name="reply_content",
            field=models.TextField(default="", help_text="Reply text content"),
        ),
        migrations.AddField(
            model_name="messagereply",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent this reply",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("order", "Order Message"), ("general", "General Support")],
                default="general",
                help_text="Type of message: order or general support",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated order for order-specific messages",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_messages",
                to="business.order",
            ),
        ),
        migrations.AlterField(
            model_name="messagereply",
            name="message",
            field=models.ForeignKey(
                help_text="Parent message this reply belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="notifications.message",
            ),
        ),
        migrations.AlterField(
            model_name="messagereply",
            name="sender_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("support", "Support"),
                    ("system", "System"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "message_type"], name="user_messag_user_id_9192c4_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="message",
            table="user_message",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="replied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who replied to this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_message_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generalmessage",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user assigned to handle this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_general_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generalmessage",
            name="replied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who replied",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="general_message_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generalmessageattachment",
            name="general_message",
            field=models.OneToOneField(
                help_text="One attachment per general message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment",
                to="notifications.generalmessage",
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="notifications.message",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["is_read"], name="contact_mes_is_read_b66dbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["replied"], name="contact_mes_replied_ebfacc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["priority"], name="contact_mes_priorit_341767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["source"], name="contact_mes_source_5bfb88_idx"),
        ),
        migrations.AddIndex(
            model_name="generalmessage",
            index=models.Index(fields=["status"], name="general_mes_status_5984a1_idx"),
        ),
        migrations.AddIndex(
            model_name="generalmessage",
            index=models.Index(
                fields=["subject"], name="general_mes_subject_14e96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generalmessage",
            index=models.Index(
                fields=["assigned_to"], name="general_mes_assigne_df2ebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generalmessage",
            index=models.Index(
                fields=["created_at"], name="general_mes_created_0f188a_idx"
            ),
        ),
    ]
