# Generated by Django 5.2.2 on 2025-12-27 18:44

from django.conf import settings
from django.db import migrations, models


def populate_conversation_ids(apps, schema_editor):
    """Populate conversation_id for existing messages"""
    Message = apps.get_model('notifications', 'Message')
    
    for message in Message.objects.all():
        if message.conversation_id:
            continue  # Already has conversation_id
            
        if message.message_type == 'order' and message.order_id:
            # For order messages, use order_id as conversation_id
            message.conversation_id = str(message.order_id)
        else:
            # For general messages, generate new UUID
            import uuid
            message.conversation_id = str(uuid.uuid4())
        
        message.save(update_fields=['conversation_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_delete_contactmessage"),
        ("notifications", "0003_contactmessage_generalmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Groups messages into conversations. For orders: uses order_id. For general: uses UUID",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation_id"], name="user_messag_convers_14ebd6_idx"
            ),
        ),
        migrations.RunPython(populate_conversation_ids, migrations.RunPython.noop),
    ]
