# Generated by Django 5.2.2 on 2026-01-01 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_delete_contactmessage"),
        ("notifications", "0005_fix_general_conversation_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("order", "Order Conversation"),
                            ("general", "General Support"),
                        ],
                        default="general",
                        help_text="Type of conversation: order or general support",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Display title for the conversation",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last message in this conversation",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversation",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="user_messag_convers_14ebd6_idx",
        ),
        migrations.RemoveField(
            model_name="message",
            name="conversation_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="order",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated order (for order conversations). OneToOne ensures one conversation per order.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="business.order",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this conversation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="The conversation this message belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="notifications.conversation",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation"], name="user_messag_convers_14ebd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "conversation_type"],
                name="conversatio_user_id_361054_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["order"], name="conversatio_order_i_f2573c_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["status"], name="conversatio_status_7e2047_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["last_message_at"], name="conversatio_last_me_888aec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation_type", "general")),
                fields=("user", "conversation_type"),
                name="unique_general_conversation_per_user",
            ),
        ),
    ]
