# Generated by Django 5.2.2 on 2026-01-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_conversation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessageReply",
        ),
    ]
