# Generated by Django 5.2.2 on 2026-01-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_delete_contactmessage"),
        ("notifications", "0007_delete_messagereply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_general_conversation_per_user",
        ),
        migrations.AddField(
            model_name="conversation",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of anonymous user (for rate limiting and abuse prevention)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session ID for anonymous users (stored in their browser localStorage)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the message sender (for anonymous users)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session ID for anonymous messages",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("order", "Order Conversation"),
                    ("general", "General Support"),
                    ("anonymous", "Anonymous Support"),
                ],
                default="general",
                help_text="Type of conversation: order, general, or anonymous support",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this conversation (null for anonymous)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("order", "Order Message"),
                    ("general", "General Support"),
                    ("anonymous", "Anonymous Support"),
                ],
                default="general",
                help_text="Type of message: order, general, or anonymous support",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("support", "Support"),
                    ("system", "System"),
                    ("anonymous", "Anonymous User"),
                ],
                default="user",
                help_text="Who sent the message",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who owns this message (null for anonymous)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["session_id"], name="conversatio_session_1a03f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session_id"], name="user_messag_session_e81b23_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("conversation_type", "general"),
                    models.Q(("user", None), _negated=True),
                ),
                fields=("user", "conversation_type"),
                name="unique_general_conversation_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("conversation_type", "anonymous"),
                    models.Q(("session_id", None), _negated=True),
                ),
                fields=("session_id",),
                name="unique_anonymous_conversation_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conversation_type", "order"),
                    ("user__isnull", False),
                    ("session_id__isnull", False),
                    _connector="OR",
                ),
                name="conversation_has_owner",
            ),
        ),
    ]
