# Generated by Django 5.2.2 on 2026-01-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0008_remove_conversation_unique_general_conversation_per_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_general_conversation_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_anonymous_conversation_per_session",
        ),
        migrations.RemoveConstraint(
            model_name="conversation",
            name="conversation_has_owner",
        ),
    ]
